#!/bin/bash
echo "════════════════════════════════════"
echo "PURPLEOCAZ SESSION START"
echo "$(date)"
echo "════════════════════════════════════"
echo ""
echo "CURRENT PRIORITY (from STANDUP.md):"
grep -A3 "PRIORITY\|TODAY\|NEXT\|priority\|Tomorrow" /root/NEW-AI-PROJECT/STANDUP.md | head -10
echo ""
echo "LAST 5 LESSONS:"
tail -15 /root/NEW-AI-PROJECT/LESSONS.md
echo ""
echo "SYSTEM HEALTH:"
echo "Clawdbot: $(systemctl is-active clawdbot 2>/dev/null || echo 'unknown')"
echo "Droplet disk: $(df -h / | tail -1 | awk '{print $5}') used"
echo "Git status: $(git -C /root/NEW-AI-PROJECT status --short | wc -l) uncommitted files"
echo ""
echo "════════════════════════════════════"
echo "READY. Read the above before starting."
echo "════════════════════════════════════"
