#!/bin/bash
echo "════════════════════════════════════"
echo "PURPLEOCAZ SESSION START"
echo "$(date)"
echo "════════════════════════════════════"
echo ""
echo "CURRENT PRIORITY (from STANDUP.md):"
grep -A3 "PRIORITY\|TODAY\|NEXT\|priority\|Tomorrow" /root/NEW-AI-PROJECT/STANDUP.md | head -10
echo ""
echo "LAST 5 LESSONS:"
tail -15 /root/NEW-AI-PROJECT/LESSONS.md
echo ""
echo "────────────────────────────────────"
echo "TOP 3 UNACTIONED IDEAS (from YT intelligence loop):"
python3 /root/NEW-AI-PROJECT/scripts/mark_idea_actioned.py --list --top 3 2>/dev/null || echo "  (backlog unavailable)"
echo ""
echo "Latest digest: $(ls -t /root/NEW-AI-PROJECT/digests/DIGEST_*.md 2>/dev/null | head -1 | xargs basename 2>/dev/null || echo 'none')"
echo "To action an idea: python3 scripts/mark_idea_actioned.py --keyword 'keyword' --note 'what you did'"
echo "────────────────────────────────────"
echo ""
echo "SYSTEM HEALTH:"
echo "Clawdbot: $(systemctl is-active clawdbot 2>/dev/null || echo 'unknown')"
echo "Droplet disk: $(df -h / | tail -1 | awk '{print $5}') used"
echo "Git status: $(git -C /root/NEW-AI-PROJECT status --short | wc -l) uncommitted files"
echo ""
echo "════════════════════════════════════"
echo "READY. Read the above before starting."
echo "════════════════════════════════════"
