#!/usr/bin/env python3
"""Weekly Digest Processor — Monday 8am UTC cron.

Reads the latest weekly digest, extracts actionable ideas via Claude API,
appends to ideas_backlog.md, and emails a summary.

Usage:
    python3 scripts/digest_processor.py
"""

import glob
import os
import sys
from datetime import datetime

import anthropic
from dotenv import load_dotenv
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, HtmlContent

load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env'))

DIGESTS_DIR = os.path.join(os.path.dirname(__file__), '..', 'digests')
BACKLOG_PATH = os.path.join(os.path.dirname(__file__), '..', 'ideas_backlog.md')

EXTRACTION_PROMPT = """You are a business intelligence analyst for PurpleOcaz, an Etsy digital products business focused on tattoo studios, beauty niches, and Canva templates.

Extract exactly 5 actionable ideas from this weekly digest. Only include ideas relevant to:
- Etsy digital product strategy
- Tattoo, beauty, hair, nail, lash niches
- Canva template creation and sales
- AI automation pipeline improvements

For each idea, provide:
- One-line description (actionable, specific)
- Effort: High / Medium / Low
- Impact: High / Medium / Low
- Suggested next step (one sentence)

Output as a clean numbered list. No preamble, no fluff, no summary paragraph.

DIGEST:
{digest_content}"""

EMAIL_TO = 'andynos2022@gmail.com'
EMAIL_FROM = 'andynos2022@gmail.com'


def get_latest_digest():
    files = sorted(glob.glob(os.path.join(DIGESTS_DIR, 'DIGEST_*.md')))
    if not files:
        print('ERROR: No digest files found', file=sys.stderr)
        sys.exit(1)
    latest = files[-1]
    with open(latest) as f:
        return latest, f.read()


def extract_ideas(digest_content):
    try:
        client = anthropic.Anthropic()
        message = client.messages.create(
            model='claude-sonnet-4-20250514',
            max_tokens=1024,
            messages=[{
                'role': 'user',
                'content': EXTRACTION_PROMPT.format(digest_content=digest_content),
            }],
        )
        return message.content[0].text
    except Exception as e:
        print(f'WARNING: Claude API call failed: {e}', file=sys.stderr)
        print('Falling back to raw digest top ideas...', file=sys.stderr)
        # Fallback: extract the TOP IDEAS section from the digest itself
        lines = digest_content.split('\n')
        ideas = []
        in_top = False
        for line in lines:
            if '## 🔥 TOP IDEAS' in line or '## TOP IDEAS' in line:
                in_top = True
                continue
            if in_top and line.startswith('## '):
                break
            if in_top and line.strip().startswith('- **'):
                ideas.append(line.strip())
        return '\n'.join(ideas) if ideas else 'No ideas extracted — Claude API unavailable and no TOP IDEAS section found.'


def append_to_backlog(ideas_text, date_str):
    header = f'\n## From Weekly Digest {date_str}\n\n'
    with open(BACKLOG_PATH, 'a') as f:
        f.write(header)
        f.write(ideas_text)
        f.write('\n')
    print(f'Appended to {BACKLOG_PATH}')


def send_email(ideas_text, digest_path, date_str):
    api_key = os.getenv('SENDGRID_API_KEY')
    if not api_key:
        print('WARNING: SENDGRID_API_KEY not set — skipping email', file=sys.stderr)
        return False

    subject = f'🧠 PurpleOcaz Weekly Intel — {date_str}'

    # Convert ideas to HTML (preserve line breaks, bold markdown)
    ideas_html = ideas_text.replace('\n', '<br>\n')
    html_body = f"""<html><body>
<h2>Weekly Digest Intelligence Extract</h2>
<p><strong>Date:</strong> {date_str}</p>
<hr>
<h3>Top 5 Ideas</h3>
<div style="font-family: sans-serif; line-height: 1.6;">
{ideas_html}
</div>
<hr>
<p style="color: #888; font-size: 12px;">
Full digest: {os.path.basename(digest_path)}<br>
Generated by digest_processor.py
</p>
</body></html>"""

    message = Mail(
        from_email=EMAIL_FROM,
        to_emails=EMAIL_TO,
        subject=subject,
        html_content=HtmlContent(html_body),
    )

    try:
        sg = SendGridAPIClient(api_key)
        response = sg.send(message)
        print(f'Email sent to {EMAIL_TO} (status: {response.status_code})')
        return True
    except Exception as e:
        print(f'WARNING: Email failed: {e}', file=sys.stderr)
        print('Ideas were still appended to backlog.', file=sys.stderr)
        return False


def main():
    print('[digest_processor] Starting...')

    digest_path, digest_content = get_latest_digest()
    date_str = datetime.now().strftime('%Y-%m-%d')
    print(f'Latest digest: {digest_path}')

    print('Extracting ideas via Claude API...')
    ideas_text = extract_ideas(digest_content)
    print(f'Extracted:\n{ideas_text}\n')

    append_to_backlog(ideas_text, date_str)
    send_email(ideas_text, digest_path, date_str)

    print('[digest_processor] Done.')


if __name__ == '__main__':
    main()
